# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.
  config.vm.network "public_network"
  config.vm.provision "shell", inline: "echo Hello"

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "bento/centos-7.2"
    # jenkins.ssh.username = "jenkins"
    # jenkins.ssh.password = "nisum5020"
    jenkins.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
      vb.name = "nisum-jenkins"
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
  end

  config.vm.define "app" do |app|
    app.vm.box = "ubuntu/trusty64"
    app.vm.provider "virtualbox" do |vb|
      # Display the VirtualBox GUI when booting the machine
      # vb.gui = true
      app.ssh.password = "nisum5020"
      vb.name = "nisum-app"
      # Customize the amount of memory on the VM:
      vb.memory = "1024"
    end
  end
end
